name: 'Hello World Action'
description: 'Prints Hello, World!'
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/hello-world.sh
      shell: bash
    - run: echo "ORG_SECRET is ${{ secrets.ORG_TEST_SECRET }}"
      shell: bash

